config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  scope module: :public do
    get "search" => "searches#search"
    get "search_results" => "searches#search_results"
  end

  scope module: :public do
    resources :reviews do
      resource :bookmarks, only: [:create, :destroy]
    end
  end

  scope module: :public do
    resources :comments, only: [:index, :edit, :create, :update, :destroy]
  end

  scope module: :public do
    resources :users, only: [:show, :edit, :update]
    get 'users/confirm' => 'users#confirm' , as: :users_canfirm
    patch 'users/my_page/cancel' => 'users#cancel' , as: :users_cancle
  end

  scope module: :public do
    root to: "homes#top"
    resources :homes, only: [:index]
  end

  namespace :admin do
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :comments, only: [:create, :update, :destroy, :index, :edit]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :keywords, only: [:index, :edit, :create, :update, :destroy]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :review
  
  validates :comment, presence: true

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @comments = Comment.all
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    comment = Comment.find(params[:id])
    comment.update(comments_params)
    redirect_to admin_comments_path
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to admin_comments_path
  end

  private

  def comments_params
    params.require(:comment).permit(:comment)
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/edit.html.erb
<div class="container" style="margin: 30px;">
  <div class="row" >
    <div class="col-md-12">
      <h1>コメント編集</h1>

      <%= form_with model: @comment , url: admin_comment_path(@comment.id) , method: :patch do |f| %>
        <%= f.text_area :comment %>
        <%= f.submit '更新' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/comments/index.html.erb
<div class="container" style="margin: 30px;">
  <div class="row" >
    <div class="col-md-12">

      <h1>コメント一覧</h1>
      <% @comments.each do |comment| %>
      <div class="col-md-12" style="padding: 10px;">
        <%=link_to comment.review.cafe_name , admin_review_path(comment.review.id) %><br>
        <%= comment.created_at.strftime('%Y/%m/%d') %><br>
        <% if comment.user.image.attached? %>
          <%= image_tag comment.user.image, class: "rounded-circle", style: "width: 50px; height: 50px;" %>
        <% else %>
          <%= image_tag 'no_image.jpg', class: "rounded-circle", style: "width: 50px; height: 50px;" %>
        <% end %>
        <%= link_to comment.user.user_name , admin_user_path(comment.user.id) %>
        <%= comment.comment %><br>
        <%= link_to '編集', edit_admin_comment_path(comment.id) %>
        <%= link_to '削除', admin_comment_path(comment.id), method: :delete , "data-confirm" => "本当に削除しますか？" %>
      </div>
      <% end %>
    </div>
  </div>
</div>