config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  scope module: :public do
    get "search" => "searches#search"
    get "search_results" => "searches#search_results"
  end

  scope module: :public do
    resources :reviews do
      resource :bookmarks, only: [:create, :destroy]
    end
  end

  scope module: :public do
    resources :comments, only: [:index, :edit, :create, :update, :destroy]
  end

  scope module: :public do
    resources :users, only: [:show, :edit, :update]
    get 'users/confirm' => 'users#confirm' , as: :users_canfirm
    patch 'users/my_page/cancel' => 'users#cancel' , as: :users_cancle
  end

  scope module: :public do
    root to: "homes#top"
    resources :homes, only: [:index]
  end

  namespace :admin do
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :comments, only: [:create, :update, :destroy, :index, :edit]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :keywords, only: [:index, :edit, :create, :update, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_one_attached :image
  
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  def self.guest
    find_or_create_by!(email: 'guest@example.com', user_name: 'ゲスト') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews
    @comments = @user.comments
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path(user.id)
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :introduction, :is_deleted)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container" style="margin: 30px;">
  <div class="row" >
    <div class="col-md-8">

      <h1>ユーザー編集</h1>
      <%= form_with model: @user, url: admin_user_path(@user.id), method: :patch do |f| %>
        <table>
        <tr>
          <th>ユーザーネーム</th><td><%= f.text_field :user_name %></td>
        </tr>
        <tr>
          <th>メールアドレス</th><td><%= f.text_field :email %></td>
        </tr>
        <tr>
          <th>自己紹介</th><td><%= f.text_area :introduction %></td>
        </tr>
        <tr>
          <th>退会ステータス</th>
          <td>
            <%= f.radio_button :is_deleted, true %>
            <%= f.label :is_deleted, '退会', value: true %>
            <%= f.radio_button :is_deleted, false %>
            <%= f.label :is_deleted, '有効', value: false %>
          </td>
        </tr>
        </table>
        <%= f.submit '更新' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container" style="margin: 30px;">
  <div class="row" >
    <div class="col-md-12">

      <h1>ユーザー一覧</h1>

        <table>
          <thead>
            <tr>
              <th style="width: 150px;">ユーザーネーム</th>
              <th style="width: 250px;">メールアドレス</th>
              <th style="width: 150px;">退会ステータス</th>
              <th></th>
            </tr>
          </thead>
          <% @users.each do |user| %>
          <tbody>
            <tr>
              <td>
                <% if user.image.attached? %>
                  <%= image_tag user.image, class: "rounded-circle", style: "width: 50px; height: 50px;" %>
                <% else %>
                  <%= image_tag 'no_image.jpg', class: "rounded-circle", style: "width: 50px; height: 50px;" %>
                <% end %>
                <%= link_to user.user_name, admin_user_path(user.id) %>
              </td>
              <td><%= user.email %></td>
              <td>
                <% if user.is_deleted == false %>
                  有効<br>
                <% else %>
                  退会<br>
                <% end %>
              </td>
              <td><%= link_to '編集', edit_admin_user_path(user.id) %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container" style="margin: 30px;">
  <div class="row">

    <h1>ユーザー詳細</h1>

  </div>

  <div class="row">
    <div class="col-md-4" style="padding: 30px;">
      <% if @user.image.attached? %>
        <%= image_tag @user.image, style: "width: 200px; height: 200px; padding: 30px;" %><br>
      <% else %>
        <%= image_tag 'no_image.jpg', style: "width: 200px; height: 200px;" %><br>
      <% end %>

      <table>
        <tr>
          <th style="width: 150px;">ユーザーネーム</th><td><%= @user.user_name %></td>
        </tr>
        <tr>
          <th>メールアドレス</th><td><%= @user.email %></td>
        </tr>
        <tr>
          <th>自己紹介</th><td><%= @user.introduction %></td>
        </tr>
        <tr>
          <th>退会ステータス</th>
          <td>
            <% if @user.is_deleted == false %>
              有効
            <% else %>
              退会
            <% end %>
          </td>
        </tr>
      </table>

      <%= link_to '編集', edit_admin_user_path(@user.id) %>

    </div>

    <div class="col-md-8">
      <h2 style="padding: 30px;">投稿一覧</h2>
      <% @reviews.each do |review| %>
        <%= image_tag review.get_image(200,200) %><br>
        <table>
          <tr>
            <th style="width: 100px;">投稿日</th><td><%= review.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <th>店舗名</th><td><%= link_to review.cafe_name , admin_review_path(review.id) %></td>
          </tr>
          <tr>
            <th>住所</th><td><%= review.address %></td>
          </tr>
          <tr>
            <th>営業時間</th><td><%= review.opening_hours %></td>
          </tr>
          <tr>
            <th>定休日</th><td><%= review.day_off %></td>
          </tr>
          <tr>
            <th>レビュー</th><td><%= review.review %></td>
          </tr>
        </table>
        <%= link_to '削除', url: admin_review_path(review.id) ,method: :delete , "data-confirm" => "本当に削除しますか？" %><br>
      <% end %>

      <h2 style="padding: 30px;">コメント一覧</h2>
      <% @comments.each do |comment| %>
        <%= link_to comment.review.cafe_name , admin_review_path(comment.review.id) %><br>
        <%= comment.created_at.strftime('%Y/%m/%d') %>
        <%= comment.comment %><br>
        <%= link_to '削除', url: admin_comment_path(comment.id), method: :delete , "data-confirm" => "本当に削除しますか？" %>
      <% end %>
    </div>
  </div>
</div>