config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  scope module: :public do
    get "search" => "searches#search"
    get "search_results" => "searches#search_results"
  end

  scope module: :public do
    resources :reviews do
      resource :bookmarks, only: [:create, :destroy]
    end
  end

  scope module: :public do
    resources :comments, only: [:index, :edit, :create, :update, :destroy]
  end

  scope module: :public do
    resources :users, only: [:show, :edit, :update]
    get 'users/confirm' => 'users#confirm' , as: :users_canfirm
    patch 'users/my_page/cancel' => 'users#cancel' , as: :users_cancle
  end

  scope module: :public do
    root to: "homes#top"
    resources :homes, only: [:index]
  end

  namespace :admin do
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
  end

  namespace :admin do
    resources :comments, only: [:create, :update, :destroy, :index, :edit]
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :keywords, only: [:index, :edit, :create, :update, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCafebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><strong>My Cafebook</strong></a>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "レビュー一覧", admin_reviews_path , class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "コメント一覧", admin_comments_path , class: 'nav-link text-dark' %>
                </li>
                <li>
                  <%= link_to 'ユーザー一覧',  admin_users_path , class: 'nav-link text-dark' %>
                </li>
                <li>
                  <%= link_to 'ログアウト', destroy_admin_session_path , method: :delete, class: 'nav-link text-dark' %>
                </li>
              <% elsif user_signed_in? %>
                <li class="nav-item">
                  <strong><%= link_to 'マイページ', user_path(current_user) , class: 'nav-link text-dark' %></strong>
                </li>
                <li class="nav-item">
                  <strong><%= link_to 'レビュー一覧', reviews_path, class: 'nav-link text-dark' %></strong>
                </li>
                <li class="nav-item">
                  <strong><%= link_to 'レビュー投稿', new_review_path, class: 'nav-link text-dark' %></strong>
                </li>
                <li class="nav-item">
                  <strong><%= link_to 'ログアウト', destroy_user_session_path , method: :delete , class: 'nav-link text-dark' %></strong>
                </li>
              <% else %>
                <li class="nav-item">
                  <strong><%= link_to 'レビュー一覧', reviews_path, class: 'nav-link text-dark' %></strong>
                </li>
                <li class="nav-item">
                  <strong><%= link_to '新規登録',  new_user_registration_path, class: 'nav-link text-dark' %></strong>
                </li>
                <li class="nav-item">
                  <strong><%= link_to 'ログイン', new_user_session_path, class: 'nav-link text-dark' %></strong>
                </li>
                <li class="nav-item">
                  <strong><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post , class: 'nav-link text-dark' %></strong>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <div style="margin: 30px;">
        <p class="text-success"><%= notice %></p>
        <p class="alert" style="color:red;"><%= alert %></p>
      </div>
      <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div style="text-align: center;">
              my cafebook.
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>